mongodb:
  database: "bible_compass"
Redis:
  redishost: "localhost"
  Redisport: "6379"
server:
  port: "3000"
  secret: "mySecretKey"
Paystack:
  initUrl: "https://api.paystack.co/transaction/initialize"
  verifyUrl: "https://api.paystack.co/transaction/verify/"
AiBible:
  url: "https://archived.getbible.net/json?passage="
