mongodb:
  # url: "mongodb+srv://e2scoba:blockchain@cluster0.b8qy1lb.mongodb.net/?retryWrites=true&w=majority"
  # url: "mongodb+srv://lordscoba:blockchain@cluster0.ah1nlqp.mongodb.net/?retryWrites=true&w=majority"
  database: "bible_compass"
Redis:
  redishost: "localhost"
  Redisport: "6379"
server:
  port: "3000"
  secret: "mySecretKey"
Paystack:
  initUrl: "https://api.paystack.co/transaction/initialize"
  verifyUrl: "https://api.paystack.co/transaction/verify/"
  # paystackKey: "sk_test_d21236670660c3ced374f520275aa2e0c364e844"
AiBible:
  url: "https://getbible.net/json?passage="
  # key: "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"
